### PR TITLE
Remove some generated files from the repository, and add a .gitignore file

### PR DESCRIPTION
**Pull request by fingolfin**
Generated files (such as the PDF and HTML files from the manual) should not be in the git repository. This PR removes them. It also adds a `.gitignore` file to help ensure they won't be added again by accident.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
@grahamknockillaree this is the common practice - not keeping autogenerated files in the repository. Instead, the release script will generate them automatically and wrap into the release archive. What we are particularly asking from you is to check the list of removed files (e.g. at https://github.com/gap-packages/hap/pull/5/commits/384a70de4f38a23f60fc9cf0754a18aaf6cbfa0e) to ensure that we did not delete accidentally something what should be there.

**Comment by fingolfin** [comment]
@grahamknockillaree is this OK for you? Or perhaps you have concerns about this proposed change?

**Comment by fingolfin** [comment]
@grahamknockillaree just to explain: all this PR does is remove a lot of files. But only files that can be regenerated, and are in fact frequently regenerated; e.g. the HTML files of the manual. Here is the full list:

```
commit 20187dc19cab8a310ca181a65204a2b297ab052c
Author: Max Horn <max@quendi.de>
Date:   2019-08-16 13:11:00 +0200

    Remove some generated files

 doc/.idl.ilg                                       |    4 -
 doc/.idl.ind                                       |    0
 doc/.ind                                           |    0
 doc/HapMan.aux                                     |  136 -
 doc/HapMan.bbl                                     |    0
 doc/HapMan.blg                                     |   48 -
 doc/HapMan.idx                                     |  558 --
 doc/HapMan.ilg                                     |    6 -
 doc/HapMan.ind                                     |  566 --
 doc/HapMan.log                                     | 9574 --------------------
 doc/HapMan.out                                     |   40 -
 doc/HapMan.pnr                                     |   43 -
 doc/HapMan.tex                                     | 4582 ----------
 doc/HapMan.toc                                     |   40 -
 doc/chap0.html                                     |  118 -
 doc/chap0.txt                                      |   46 -
 doc/chap1.html                                     | 1689 ----
 doc/chap1.txt                                      |  126 -
 doc/chap10.html                                    |  107 -
 doc/chap10.txt                                     |   17 -
 doc/chap11.html                                    |  291 -
 doc/chap11.txt                                     |   30 -
 doc/chap12.html                                    |   82 -
 doc/chap12.txt                                     |   10 -
 doc/chap13.html                                    |  112 -
 doc/chap13.txt                                     |   10 -
 doc/chap14.html                                    |   62 -
 doc/chap14.txt                                     |   10 -
 doc/chap15.html                                    |  186 -
 doc/chap15.txt                                     |   18 -
 doc/chap16.html                                    |  119 -
 doc/chap16.txt                                     |   11 -
 doc/chap17.html                                    |   93 -
 doc/chap17.txt                                     |    9 -
 doc/chap18.html                                    |  148 -
 doc/chap18.txt                                     |   13 -
 doc/chap19.html                                    |   64 -
 doc/chap19.txt                                     |    8 -
 doc/chap2.html                                     |  569 --
 doc/chap2.txt                                      |   56 -
 doc/chap20.html                                    |   91 -
 doc/chap20.txt                                     |   13 -
 doc/chap21.html                                    |  191 -
 doc/chap21.txt                                     |   26 -
 doc/chap22.html                                    |   59 -
 doc/chap22.txt                                     |    7 -
 doc/chap23.html                                    |   77 -
 doc/chap23.txt                                     |    9 -
 doc/chap24.html                                    |   86 -
 doc/chap24.txt                                     |   12 -
 doc/chap25.html                                    |  160 -
 doc/chap25.txt                                     |   20 -
 doc/chap26.html                                    |  137 -
 doc/chap26.txt                                     |   23 -
 doc/chap27.html                                    |  105 -
 doc/chap27.txt                                     |   17 -
 doc/chap28.html                                    |  168 -
 doc/chap28.txt                                     |   28 -
 doc/chap29.html                                    |  300 -
 doc/chap29.txt                                     |   54 -
 doc/chap3.html                                     |  160 -
 doc/chap3.txt                                      |   21 -
 doc/chap30.html                                    |   76 -
 doc/chap30.txt                                     |   10 -
 doc/chap31.html                                    |   86 -
 doc/chap31.txt                                     |   12 -
 doc/chap32.html                                    |  173 -
 doc/chap32.txt                                     |   31 -
 doc/chap33.html                                    |   92 -
 doc/chap33.txt                                     |   14 -
 doc/chap34.html                                    |  155 -
 doc/chap34.txt                                     |   28 -
 doc/chap35.html                                    |  124 -
 doc/chap35.txt                                     |   20 -
 doc/chap36.html                                    |   89 -
 doc/chap36.txt                                     |   13 -
 doc/chap37.html                                    |   62 -
 doc/chap37.txt                                     |    8 -
 doc/chap38.html                                    |   89 -
 doc/chap38.txt                                     |   13 -
 doc/chap39.html                                    |  118 -
 doc/chap39.txt                                     |   18 -
 doc/chap4.html                                     |   94 -
 doc/chap4.txt                                      |    8 -
 doc/chap5.html                                     |  258 -
 doc/chap5.txt                                      |   32 -
 doc/chap6.html                                     |   47 -
 doc/chap6.txt                                      |    5 -
 doc/chap7.html                                     |   64 -
 doc/chap7.txt                                      |    5 -
 doc/chap8.html                                     |  118 -
 doc/chap8.txt                                      |   18 -
 doc/chap9.html                                     |   97 -
 doc/chap9.txt                                      |   13 -
 doc/chapInd.html                                   |  527 --
 doc/chapInd.txt                                    |  495 -
 doc/manual.pdf                                     |  Bin 332302 -> 0 bytes
 doc/manual.six                                     | 1197 ---
 doc/newman/ChildCreate.log                         |   82 -
 doc/newman/HenonOrbit.log                          |  119 -
 doc/newman/q.log                                   | 1200 ---
 pdfdoc/newman/ActedGroup.xml                       |    9 -
 pdfdoc/newman/ActingGroup.xml                      |    9 -
 pdfdoc/newman/AlexanderPolynomial.xml              |   12 -
 pdfdoc/newman/AreIsomorphicGradedAlgebras.xml      |   10 -
 pdfdoc/newman/BarCodeCompactDisplay.xml            |    7 -
 pdfdoc/newman/BarCodeDisplay.xml                   |    7 -
 pdfdoc/newman/BettiNumber.xml                      |   29 -
 pdfdoc/newman/BoundaryMap.xml                      |    9 -
 pdfdoc/newman/BoundaryPair.xml                     |    9 -
 pdfdoc/newman/CayleyGraphOfGroup.xml               |    6 -
 pdfdoc/newman/CayleyGraphOfGroupDisplay.xml        |    6 -
 pdfdoc/newman/CayleyMetric.xml                     |    8 -
 pdfdoc/newman/CcGroup.xml                          |   13 -
 pdfdoc/newman/Centre.xml                           |    7 -
 pdfdoc/newman/ChainComplex.xml                     |   16 -
 pdfdoc/newman/ChainComplexEquivalence.xml          |    8 -
 pdfdoc/newman/ChainComplexOfQuotient.xml           |    7 -
 pdfdoc/newman/ChainMap.xml                         |   23 -
 pdfdoc/newman/ChevalleyEilenbergComplex.xml        |   10 -
 pdfdoc/newman/ChildCommand.xml                     |    7 -
 pdfdoc/newman/ChildCreate.xml                      |   14 -
 pdfdoc/newman/ChildGet.xml                         |    8 -
 pdfdoc/newman/ChildIsAvailable.xml                 |    7 -
 pdfdoc/newman/ChildKill.xml                        |    9 -
 pdfdoc/newman/ChildPut.xml                         |    8 -
 pdfdoc/newman/CliqueComplex.xml                    |   22 -
 pdfdoc/newman/CochainComplex.xml                   |   21 -
 pdfdoc/newman/CocycleCondition.xml                 |   14 -
 pdfdoc/newman/Cohomology.xml                       |   22 -
 pdfdoc/newman/CohomologyModule.xml                 |   12 -
 pdfdoc/newman/ConcentricFiltration.xml             |   11 -
 pdfdoc/newman/ContractedComplex.xml                |   22 -
 pdfdoc/newman/ContractibleSubcomplex.xml           |    8 -
 pdfdoc/newman/CriticalCells.xml                    |    8 -
 pdfdoc/newman/CubicalComplex.xml                   |    6 -
 pdfdoc/newman/CupProduct.xml                       |   18 -
 pdfdoc/newman/DendrogramMat.xml                    |   18 -
 pdfdoc/newman/DiagonalApproximation.xml            |   14 -
 pdfdoc/newman/DirectProduct.xml                    |    8 -
 pdfdoc/newman/Display.xml                          |    9 -
 pdfdoc/newman/DisplayArcPresentation.xml           |    7 -
 pdfdoc/newman/DisplayCSVknotFile.xml               |    7 -
 pdfdoc/newman/DisplayDendrogram.xml                |    8 -
 pdfdoc/newman/DisplayDendrogramMat.xml             |    8 -
 pdfdoc/newman/DisplayPDBfile.xml                   |   10 -
 pdfdoc/newman/EquivariantChainMap.xml              |   14 -
 pdfdoc/newman/EquivariantEuclideanSpace.xml        |    6 -
 pdfdoc/newman/EquivariantOrbitPolytope.xml         |    6 -
 pdfdoc/newman/EquivariantTwoComplex.xml            |    6 -
 pdfdoc/newman/EuclideanMetric.xml                  |    9 -
 pdfdoc/newman/EuclideanSquaredMetric.xml           |    9 -
 pdfdoc/newman/EulerCharacteristic.xml              |   18 -
 pdfdoc/newman/EulerIntegral.xml                    |   10 -
 pdfdoc/newman/FilteredTensorWithIntegers.xml       |   10 -
 pdfdoc/newman/FilteredTensorWithIntegersModP.xml   |   10 -
 pdfdoc/newman/FiltrationTerm.xml                   |    6 -
 pdfdoc/newman/FreeGResolution.xml                  |   15 -
 pdfdoc/newman/FundamentalGroup.xml                 |   19 -
 pdfdoc/newman/FundamentalGroupOfQuotient.xml       |    8 -
 pdfdoc/newman/GOuterGroup.xml                      |   14 -
 pdfdoc/newman/Graph.xml                            |    7 -
 pdfdoc/newman/GroupAlgebraAsFpGModule.xml          |    6 -
 pdfdoc/newman/GroupCohomology.xml                  |   11 -
 pdfdoc/newman/GroupHomology.xml                    |   11 -
 pdfdoc/newman/HAPDerivation.xml                    |   11 -
 pdfdoc/newman/HammingMetric.xml                    |    7 -
 pdfdoc/newman/HenonOrbit.xml                       |   10 -
 pdfdoc/newman/HilbertPoincareSeries.xml            |    7 -
 pdfdoc/newman/HomToGModule.xml                     |    7 -
 pdfdoc/newman/HomToIntegers.xml                    |   18 -
 pdfdoc/newman/HomToIntegralModule.xml              |   14 -
 pdfdoc/newman/Homology.xml                         |   21 -
 pdfdoc/newman/HomologyOfDerivation.xml             |   10 -
 pdfdoc/newman/HomotopyGraph.xml                    |   10 -
 pdfdoc/newman/IntegralCohomologyGenerators.xml     |   15 -
 pdfdoc/newman/IsAspherical.xml                     |    7 -
 pdfdoc/newman/KendallMetric.xml                    |    9 -
 pdfdoc/newman/KnotGroup.xml                        |    7 -
 pdfdoc/newman/KnotReflection.xml                   |    5 -
 pdfdoc/newman/KnotSum.xml                          |    5 -
 pdfdoc/newman/LHSSpectralSequence.xml              |    9 -
 pdfdoc/newman/LHSSpectralSequenceLastSheet.xml     |    8 -
 pdfdoc/newman/LeibnizAlgebraHomology.xml           |    8 -
 pdfdoc/newman/LeibnizComplex.xml                   |    9 -
 pdfdoc/newman/LieAlgebraHomology.xml               |    8 -
 pdfdoc/newman/ManhattanMetric.xml                  |    8 -
 pdfdoc/newman/Mod2CohomologyRingPresentation.xml   |   22 -
 pdfdoc/newman/ModPCohomologyGenerators.xml         |   21 -
 pdfdoc/newman/ModPCohomologyRing.xml               |   35 -
 pdfdoc/newman/Nerve.xml                            |   12 -
 pdfdoc/newman/OrbitPolytope.xml                    |   21 -
 pdfdoc/newman/OrientRegularCWComplex.xml           |    7 -
 pdfdoc/newman/PathComponent.xml                    |    9 -
 pdfdoc/newman/PersistentBettiNumbers.xml           |   29 -
 pdfdoc/newman/PiZero.xml                           |   10 -
 pdfdoc/newman/PoincareSeries.xml                   |   22 -
 pdfdoc/newman/PoincareSeriesPrimePart.xml          |   10 -
 pdfdoc/newman/PrimePartDerivedFunctor.xml          |    6 -
 pdfdoc/newman/PureComplexBoundary.xml              |   12 -
 pdfdoc/newman/PureComplexComplement.xml            |   10 -
 pdfdoc/newman/PureComplexDifference.xml            |   10 -
 pdfdoc/newman/PureComplexIntersection.xml          |   10 -
 pdfdoc/newman/PureComplexThickened.xml             |   10 -
 pdfdoc/newman/PureComplexUnion.xml                 |   10 -
 pdfdoc/newman/PureCubicalComplex.xml               |    6 -
 pdfdoc/newman/PureCubicalKnot.xml                  |   12 -
 pdfdoc/newman/PurePermutahedralComplex.xml         |    7 -
 pdfdoc/newman/PurePermutahedralKnot.xml            |   12 -
 pdfdoc/newman/QuillenComplex.xml                   |    6 -
 pdfdoc/newman/Radical.xml                          |    7 -
 pdfdoc/newman/RadicalSeries.xml                    |    9 -
 pdfdoc/newman/RandomSimplicialGraph.xml            |    9 -
 pdfdoc/newman/RandomSimplicialTwoComplex.xml       |   10 -
 pdfdoc/newman/RankHomologyPGroup.xml               |    5 -
 pdfdoc/newman/ReadCSVfileAsPureCubicalKnot.xml     |   23 -
 .../ReadImageAsFilteredPureCubicalComplex.xml      |   15 -
 pdfdoc/newman/ReadImageAsPureCubicalComplex.xml    |   12 -
 pdfdoc/newman/ReadImageAsWeightFunction.xml        |   15 -
 pdfdoc/newman/ReadPDBfileAsPureCubicalComplex.xml  |   18 -
 .../ReadPDBfileAsPurePermutahedralComplex.xml      |   18 -
 pdfdoc/newman/RegularCWComplex.xml                 |   16 -
 pdfdoc/newman/RegularCWMap.xml                     |    6 -
 pdfdoc/newman/RegularCWPolytope.xml                |    9 -
 pdfdoc/newman/ResolutionBieberbachGroup.xml        |   22 -
 pdfdoc/newman/ResolutionCubicalCrystGroup.xml      |   21 -
 pdfdoc/newman/ResolutionFiniteGroup.xml            |   16 -
 pdfdoc/newman/ResolutionNilpotentGroup.xml         |   16 -
 pdfdoc/newman/ResolutionNormalSeries.xml           |   17 -
 pdfdoc/newman/ResolutionPrimePowerGroup.xml        |   16 -
 pdfdoc/newman/ResolutionSL2Z.xml                   |   15 -
 pdfdoc/newman/ResolutionSmallGroup.xml             |   22 -
 pdfdoc/newman/ResolutionSubgroup.xml               |    7 -
 pdfdoc/newman/ResolutionSubnormalSeries.xml        |   18 -
 pdfdoc/newman/RestrictedEquivariantCWComplex.xml   |    6 -
 pdfdoc/newman/ScatterPlot.xml                      |    7 -
 pdfdoc/newman/SimplicialComplex.xml                |    8 -
 pdfdoc/newman/SimplifiedComplex.xml                |   17 -
 pdfdoc/newman/Size.xml                             |   12 -
 pdfdoc/newman/StandardCocycle.xml                  |   11 -
 pdfdoc/newman/SymmetricMatrixToFilteredGraph.xml   |   16 -
 pdfdoc/newman/SymmetricMatrixToGraph.xml           |   10 -
 pdfdoc/newman/TensorProduct.xml                    |   12 -
 pdfdoc/newman/TensorWithIntegers.xml               |   15 -
 pdfdoc/newman/TensorWithIntegersModP.xml           |   18 -
 pdfdoc/newman/ThickeningFiltration.xml             |   10 -
 pdfdoc/newman/VectorsToSymmetricMatrix.xml         |   11 -
 pdfdoc/newman/ZigZagContractedComplex.xml          |   13 -
 248 files changed, 28711 deletions(-)
```

**Comment by alex-konovalov** [comment]
@grahamknockillaree have you seen this pull request?

**Comment by grahamknockillaree** [comment]
I've now confirmed the pull request.

Graham



________________________________________

**Pull request merged**
