### PR TITLE
Fixed broken links

### PR DESCRIPTION
**Pull request by narc-Ontakac2**
Fixed broken links found with wget -r -nv --spider on a local copy.  

Links to /www/SideLinks/About/carlson.pdf and /hapcocyclic.dev.1.tar.gz  were not fixable and should most likely be removed or replaced with eternal links.

The fix that removes /www/SideLinks/About/aboutCrossedMods needs doc/Undocumented.xml to be regenerated.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
This looks sensible to me, but can't be merged now due to conflicts. Perhaps some files are autogenerated and doesn't have to be manually updated? That's a question for @grahamknockillaree.

**Comment by fingolfin** [comment]
Actually it can be "merged" or "squashed" just fine, only "rebase" is not possible.

**Comment by fingolfin** [comment]
@grahamknockillaree it'd be nice if this and my other PR were merged

**Comment by grahamknockillaree** [comment]
I'd like to merge #58 but for some reason I don't see any "merge" icon.

**Review by grahamknockillaree — APPROVED** [review]

**Review by grahamknockillaree — APPROVED** [review]

**Comment by fingolfin** [comment]
I've merged it for you

**Pull request merged**
