### PR TITLE
Install singular and polymake for Travis CI tests

### PR DESCRIPTION
**Pull request by alex-konovalov**
This PR installs polymake and singular. It will hopefully fix tests - let's wait for Travis CI results.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
All tests have timeout on `tst/testall/1.8.1.tst`, e.g.
```
testing: /home/travis/build/gap-packages/hap/gaproot/pkg/hap/tst/testall/1.8.1\
.tst
# line 9 of 26 (34%)polymake: used package ppl
  The Parma Polyhedra Library (PPL): A C++ library for convex polyhedra
  and other numerical abstractions.
  http://www.cs.unipr.it/ppl/
polymake: used package ppl
  The Parma Polyhedra Library (PPL): A C++ library for convex polyhedra
  and other numerical abstractions.
  http://www.cs.unipr.it/ppl/
# line 22 of 26 (84%)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```
but some previous tests using polymake apparently pass, and some previously seen errors disappeared, so this PR (now also incorporating #20) seems to have some effect. I suggest to merge it, and then you can start to remove tests which are not suitable for Travis to test them only manually (for now). `testall.g` only tests the `testall` directory, so you can have `tst/testextra` directory with extra tests.

**Comment by grahamknockillaree** [comment]
So should I merge pull request?

**Comment by grahamknockillaree** [comment]
In addition to Polymake and Singular, some of the tests use

Exec("perl ...")
Exec("convert ...")
Exec("ls ...")
Exec("rm ...")

Are the "per"l and "convert" available?

**Comment by alex-konovalov** [comment]
@grahamknockillaree let's merge this first, then investigate perl and convert. Do you see tests that use them failing?

**Pull request merged**
