### PR TITLE
Update some URLs from http to https

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@grahamknockillaree I hope this PR is ok for you to merge? Same for my other one, PR #66

**Review by grahamknockillaree — APPROVED** [review]

**Comment by grahamknockillaree** [comment]
The files
www/SideLinks/About/NewaboutModPRings.html
www/SideLinks/About/OLDaboutModPRings.html 
have been removed in the previous commit. So they now need to be removed from this commit before I can merge it. I don't know how to do this myself!

**Comment by fingolfin** [comment]
PR updated

**Review by grahamknockillaree — APPROVED** [review]
Thanks!

**Pull request merged**
