### PR TITLE
Add gh-pages and tmp to .gitignore

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
I should note that this added 70 MB of data to my repository clone... Most of these don't matter in the repository, as git detects that all the text files are merely copies of existing files, so they add almost no overhead. But `tmp/hap-1.30.tar.gz` is a 19 MB blob which is now permanently in the repository... :-(

**Comment by grahamknockillaree** [comment]
I've deleted tmp and gh-pages.  I should have spotted them myself. Thanks!

**Comment by fingolfin** [comment]
OK but let's also update `.gitignore` -- I've update this PR to do only that

**Comment by fingolfin** [comment]
Oops, in fact I pushed the .gitignore update directly by accident.... So @grahamknockillaree should `git pull` before doing more work

**Pull request closed without merging**
