### PR TITLE
Switch CI to use GitHub Actions

### PR DESCRIPTION
**Pull request by fingolfin**
Alternative to PR #45 by @ssiccha (created from my script to match most other packages)

### CODE REVIEW

**Comment by fingolfin** [comment]
@grahamknockillaree I've tried to fix your attempts to migrate to GitHub Actions in this PR. Let's see if the tests pass.

**Comment by grahamknockillaree** [comment]
@fingolfin  Thanks!  Fingers crossed.

**Comment by grahamknockillaree** [comment]
@fingolfin  @alex-konovalov   Thanks for your help with this migration to GitHub Actions -- the migration seems to be successful.

I see that HAP tests that make calls to Polymake are now giving errors. I seem to remember that I was unable to install the latest version of Polymake on my Laptop for some reason (which I've forgotten). Do you know the version of Polymake used in GitHub Actions?

**Comment by fingolfin** [comment]
@grahamknockillaree I see no such errors (all tests are green) -- can you pinpoint me (i.e., give the URL of a page showing the error, and perhaps indicate the error message to look for)

**Comment by grahamknockillaree** [comment]
@fingolfin   https://github.com/gap-packages/hap/runs/2289828600?check_suite_focus=true  has quite a few errors highlighted in pink. I think they are all connected with Polymake.

**Comment by fingolfin** [comment]
OK, so the first major issue is that it marks the test as "passing" when it actually failed. I'll first submit a fix for that, then we can see further.

**Pull request merged**
